name: autothread_functional_tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Lint with black
        run: |
          black --check autothread/__init__.py
          black --check autothread/test.py
      - name: Test multiprocessing
        if: ${{ matrix.os == 'ubuntu-latest'}}
        env:
          AUTOTHREAD_UNITTEST_MODE: processed
        run: |
          python -m coverage run -m unittest
      - name: Test multiprocessing
        if: ${{ matrix.os == 'windows-latest'}}
        env:
          AUTOTHREAD_UNITTEST_MODE: processed
        run: |
          python -m coverage run -m unittest || echo ERROR && exit /b
      - name: Test threading
        env:
          AUTOTHREAD_UNITTEST_MODE: threaded
        run: |
          python -m coverage run --append -m unittest
      - name: Get Coverage
        run: |
          python -m coverage report --include autothread/__init__.py --show-missing
